name: flutter_wanandroid
description: flutter wanandroid project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  ##https://github.com/ajinasokan/flutter_displaymode
  flutter_displaymode: ^0.3.2
  ##https://pub.dev/packages/lottie
  lottie: ^1.3.0
  dio: ^4.0.6
  json_annotation: ^4.5.0
  pull_to_refresh: ^2.0.0
  #https://pub.dev/packages/riverpod
  flutter_riverpod: ^2.0.0-dev.9
  flutter_inappwebview: ^5.3.2
  event_bus: ^2.0.0
  fluttertoast: ^8.0.9

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.1.5

  json_serializable: ^6.2.0
  json_model: ^1.0.0





flutter:

  uses-material-design: true

  assets:
    - assets/
